timezone: Pacific/Auckland
generator:
  metadata:
    markdown: markdown-it
    markdown-it:
      html: true
      linkify: true
paths:
  data: data
  static: "public"
  uploads: public/images
collections_config:
  pages:
    path: src/content/pages
    url: "/[full_slug]/"
    output: true
    icon: laptop_mac
    _enabled_editors:
      - visual
    filter:
      base: strict
    add_options:
      - name: Add New Page
        schema: default
        icon: pages
    schemas:
      default:
        name: New Page
        path: schemas/page.md
        remove_extra_inputs: false
    create:
      path: "[relative_base_path]/{title|slugify}.md"
  data:
    path: data
    disable_add: true
    disable_add_folder: true
    _inputs:
      colors[*]:
        options:
          preview:
            icon: palette
      value:
        type: color
      icons:
        comment: Add an icon from the list of [Font Awesome icons](https://fontawesome.com/search?o=r&m=free). Then add it to the ```src/components/utility/icon.jsx``` file, following the existing pattern.

data_config:
  icons:
    path: data/icons.json
