# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: 3d Solar System
  description: A 3d model of a solar system
  icon: "3d_rotation"
  tags:
    - 3D
    - Three.js
    - Solar system

# Defines the structure of this component, as well as the default values
blueprint:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
